package app.yukine.ui

import android.os.Build
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class EchoMobileLayoutContractTest {
    @Test
    fun glassDefaultsUseRenderEffectOnAndroid12AndTransparentFallbackBelow() {
        assertEquals(Build.VERSION_CODES.S, EchoGlassDefaults.RENDER_EFFECT_MIN_API)
        assertEquals(18f, EchoGlassDefaults.BLUR_RADIUS_DP)
        assertEquals(4f, EchoGlassDefaults.MIN_BLUR_RADIUS_DP)
        assertEquals(64f, EchoGlassDefaults.MAX_BLUR_RADIUS_DP)
        assertEquals(4f, EchoGlassDefaults.normalizeBlurRadius(-10f))
        assertEquals(64f, EchoGlassDefaults.normalizeBlurRadius(80f))
        assertEquals(18f, EchoGlassDefaults.normalizeBlurRadius(Float.NaN))
        assertEquals(0.62f, EchoGlassDefaults.SURFACE_OPACITY)
        assertEquals(0.4f, EchoGlassDefaults.normalizeSurfaceOpacity(0f))
        assertEquals(1f, EchoGlassDefaults.normalizeSurfaceOpacity(2f))
        assertEquals(1.08f, EchoGlassDefaults.SATURATION)
        assertEquals(0.72f, EchoGlassDefaults.ALPHA)

        val spec = EchoGlassSpec()
        assertEquals(EchoGlassDefaults.BLUR_RADIUS_DP, spec.blurRadiusDp)
        assertEquals(EchoGlassDefaults.SATURATION, spec.saturation)
        assertEquals(EchoGlassDefaults.ALPHA, spec.alpha)
    }

    @Test
    fun mobileShellMetricsMatchDesktopInspiredP0LayoutContract() {
        assertEquals(24f, EchoBackgroundBlurDefaults.DEFAULT_RADIUS_DP)
        assertEquals(4f, EchoBackgroundBlurDefaults.MIN_RADIUS_DP)
        assertEquals(64f, EchoBackgroundBlurDefaults.MAX_RADIUS_DP)
        assertEquals(24f, EchoBackgroundBlurDefaults.normalizeRadius(Float.NaN))
        assertEquals(4f, EchoBackgroundBlurDefaults.normalizeRadius(-5f))
        assertEquals(64f, EchoBackgroundBlurDefaults.normalizeRadius(80f))
        assertEquals(244f, EchoPageDefaults.bottomPadding.value)
        assertEquals(6f, EchoElevations.card.value)
        assertEquals(10f, EchoElevations.chrome.value)
        assertEquals(148f, EchoMobileLayoutMetrics.nowBarHeight.value)
        assertEquals(EchoMobileLayoutMetrics.nowBarHeight, EchoMobileLayoutMetrics.nowBarExpandedHeight)
        assertEquals(48f, EchoMobileLayoutMetrics.nowBarArtworkSize.value)
        assertEquals(6f, EchoMobileLayoutMetrics.nowBarArtworkCornerRadius.value)
        assertEquals(18f, EchoMobileLayoutMetrics.nowBarProgressHeight.value)
        assertEquals(1.5f, EchoMobileLayoutMetrics.nowBarScrollTranslation.value)
        assertEquals(0.985f, EchoMobileLayoutMetrics.nowBarScrollScale)
        assertEquals(0.25f, EchoMobileLayoutMetrics.nowBarScrollStretchTranslation.value)
        assertEquals(1.008f, EchoMobileLayoutMetrics.nowBarScrollStretchScale)
        assertEquals(0.75f, EchoMobileLayoutMetrics.bottomTabScrollTranslation.value)
        assertEquals(0.99f, EchoMobileLayoutMetrics.bottomTabScrollScale)
        assertEquals(0.25f, EchoMobileLayoutMetrics.bottomTabScrollStretchTranslation.value)
        assertEquals(1.006f, EchoMobileLayoutMetrics.bottomTabScrollStretchScale)
        assertEquals(250L, EchoMobileLayoutMetrics.nowBarScrollRestoreDelayMs)
        assertEquals(0.90f, EchoMobileLayoutMetrics.nowBarCompactShadowFactor)
        assertEquals(0.94f, EchoMobileLayoutMetrics.nowBarCompactLyricsAlpha)
        assertEquals(168f, EchoMobileLayoutMetrics.nowBarDockedWidth.value)
        assertEquals(40f, EchoMobileLayoutMetrics.nowBarDockedHeight.value)
        assertEquals(188f, EchoMobileLayoutMetrics.nowBarTopCloudWidth.value)
        assertEquals(38f, EchoMobileLayoutMetrics.nowBarTopCloudHeight.value)
        assertEquals(304f, EchoMobileLayoutMetrics.nowBarTopCloudExpandedWidth.value)
        assertEquals(52f, EchoMobileLayoutMetrics.nowBarTopCloudExpandedHeight.value)
        assertEquals(72f, EchoMobileLayoutMetrics.nowBarTopCloudCollapsedWidth.value)
        assertEquals(8f, EchoMobileLayoutMetrics.nowBarTopCloudCollapsedHeight.value)
        assertEquals(8f, EchoMobileLayoutMetrics.nowBarTopCloudOffset.value)
        assertEquals(0f, EchoMobileLayoutMetrics.nowBarTopCloudCollapsedOffset.value)
        assertEquals(52f, EchoMobileLayoutMetrics.nowBarTopCloudContentClearance.value)
        assertEquals(66f, EchoMobileLayoutMetrics.nowBarTopCloudExpandedContentClearance.value)
        assertEquals(14f, EchoMobileLayoutMetrics.nowBarTopCloudCollapsedContentClearance.value)
        assertEquals(1f, EchoMobileLayoutMetrics.nowBarDockedBottomPadding.value)
        assertEquals(24f, EchoMobileLayoutMetrics.nowBarDockSwipeDistance.value)
        assertEquals(24f, EchoMobileLayoutMetrics.nowBarTopCloudEnterDistance.value)
        assertEquals(32f, EchoMobileLayoutMetrics.nowBarTopCloudRestoreDistance.value)
        assertEquals(500f, EchoMobileLayoutMetrics.nowBarDockSwipeVelocityDpPerSecond)
        assertEquals(500f, EchoMobileLayoutMetrics.nowBarTopCloudSwipeVelocityDpPerSecond)
        assertEquals(1.2f, EchoMobileLayoutMetrics.nowBarDockHorizontalRatio)
        assertEquals(1.5f, EchoMobileLayoutMetrics.nowBarDockVerticalRatio)
        assertEquals(0.35f, EchoMobileLayoutMetrics.nowBarTopCloudDiagonalDockRatio)
        assertEquals(420, EchoMobileLayoutMetrics.nowBarDockMoveDurationMs)
        assertEquals(420, EchoMobileLayoutMetrics.nowBarDockSizeDurationMs)
        assertEquals(22f, EchoMobileLayoutMetrics.bottomTabIconSize.value)
        assertEquals(8f, EchoMobileLayoutMetrics.bottomTabVerticalPadding.value)
        assertEquals(12f, EchoMobileLayoutMetrics.floatingChromeHorizontalPadding.value)
        assertEquals(3f, EchoMobileLayoutMetrics.floatingChromeGap.value)
        assertEquals(10f, EchoMobileLayoutMetrics.floatingChromeBottomPadding.value)
        assertEquals(10f, EchoMobileLayoutMetrics.floatingChromeElevation.value)
        assertEquals(220f, EchoMobileLayoutMetrics.nowPlayingArtworkSize.value)
        assertEquals(12f, EchoMobileLayoutMetrics.nowPlayingArtworkCornerRadius.value)
        assertEquals(300f, EchoMobileLayoutMetrics.lyricsPanelMinHeight.value)
        assertEquals(380f, EchoMobileLayoutMetrics.lyricsPanelMaxHeight.value)
        assertEquals(292f, EchoMobileLayoutMetrics.lyricsListHeight.value)
        assertTrue(EchoMobileLayoutMetrics.lyricsPanelMaxHeight > EchoMobileLayoutMetrics.lyricsPanelMinHeight)
    }
}
