package app.yukine.ui

import androidx.compose.ui.graphics.Color

data class EchoThemePresetTone(
    val appBg: Long,
    val appBg2: Long,
    val appBg3: Long,
    val panel: Long,
    val panelSoft: Long,
    val border: Long,
    val shadow: Long,
    val text: Long,
    val heading: Long,
    val muted: Long,
    val subtle: Long,
    val accent: Long,
    val accentStrong: Long,
    val secondary: Long,
    val success: Long,
    val onAccent: Long
) {
    fun toPalette(): EchoPalette = EchoPalette(
        background = Color(appBg),
        surface = Color(panel),
        surfaceVariant = Color(panelSoft),
        panel = Color(panelSoft),
        accent = Color(accent),
        accentSoft = Color(accent).copy(alpha = 0.14f),
        text = Color(text),
        muted = Color(muted),
        highlight = Color(accent).copy(alpha = 0.12f),
        border = Color(border).copy(alpha = 0.32f),
        onAccent = Color(onAccent),
        backgroundAlt = Color(appBg2),
        backgroundDeep = Color(appBg3),
        heading = Color(heading),
        subtle = Color(subtle),
        accentStrong = Color(accentStrong),
        secondary = Color(secondary),
        success = Color(success),
        shadow = Color(shadow),
        glass = EchoGlassSpec()
    )
}

data class EchoThemePreset(
    val id: String,
    val label: String,
    val light: EchoThemePresetTone,
    val dark: EchoThemePresetTone
)

object EchoThemePresets {
    val all: List<EchoThemePreset> = listOf(
        EchoThemePreset(
            id = "classic",
            label = "Classic",
            light =             EchoThemePresetTone(
                appBg = 0xFFF6F6F7,
                appBg2 = 0xFFEDEEF0,
                appBg3 = 0xFFE6E7EA,
                panel = 0xFFFFFFFF,
                panelSoft = 0xFFEFF0F2,
                border = 0xFF26282E,
                shadow = 0xFF242730,
                text = 0xFF2D3036,
                heading = 0xFF1E2025,
                muted = 0xFF6C7179,
                subtle = 0xFF73767A,
                accent = 0xFF4B55E8,
                accentStrong = 0xFF3239C7,
                secondary = 0xFF727987,
                success = 0xFF566A5D,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF101318,
                appBg2 = 0xFF151A22,
                appBg3 = 0xFF111827,
                panel = 0xFF1C222B,
                panelSoft = 0xFF161B23,
                border = 0xFF647C96,
                shadow = 0xFF000000,
                text = 0xFFD8E0EA,
                heading = 0xFFF8FBFF,
                muted = 0xFFA8B5C4,
                subtle = 0xFF7F8B9A,
                accent = 0xFF75B7FF,
                accentStrong = 0xFFCCE6FF,
                secondary = 0xFF7DD7CB,
                success = 0xFFB9EEE8,
                onAccent = 0xFF0F1720
            )
        ),
        EchoThemePreset(
            id = "echoTwilight",
            label = "Echo Twilight",
            light =             EchoThemePresetTone(
                appBg = 0xFFFFF4EF,
                appBg2 = 0xFFF3D7CF,
                appBg3 = 0xFFEFE5F2,
                panel = 0xFFFFFCF9,
                panelSoft = 0xFFFBE9E4,
                border = 0xFFB87065,
                shadow = 0xFF6A3D37,
                text = 0xFF4F3833,
                heading = 0xFF352321,
                muted = 0xFF765D57,
                subtle = 0xFF9A817A,
                accent = 0xFFDF6B5F,
                accentStrong = 0xFFA83E37,
                secondary = 0xFF6AAEA8,
                success = 0xFF276B65,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF151012,
                appBg2 = 0xFF211719,
                appBg3 = 0xFF171320,
                panel = 0xFF271E21,
                panelSoft = 0xFF1F181B,
                border = 0xFFDF8479,
                shadow = 0xFF000000,
                text = 0xFFF3E3DE,
                heading = 0xFFFFF7F4,
                muted = 0xFFD2B9B2,
                subtle = 0xFFA98D87,
                accent = 0xFFE2776D,
                accentStrong = 0xFFFFD0CA,
                secondary = 0xFF8FD4CE,
                success = 0xFFB9EEE8,
                onAccent = 0xFF2B1513
            )
        ),
        EchoThemePreset(
            id = "sakuraMilk",
            label = "Sakura Milk",
            light =             EchoThemePresetTone(
                appBg = 0xFFFFF6F9,
                appBg2 = 0xFFF7D9E7,
                appBg3 = 0xFFF0EEFC,
                panel = 0xFFFFFDFE,
                panelSoft = 0xFFFCE8F0,
                border = 0xFFB05D7C,
                shadow = 0xFF66354A,
                text = 0xFF55333F,
                heading = 0xFF361F29,
                muted = 0xFF765B66,
                subtle = 0xFF9B7F89,
                accent = 0xFFCF5D7D,
                accentStrong = 0xFF9A3157,
                secondary = 0xFF5F9FAD,
                success = 0xFF236775,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF151015,
                appBg2 = 0xFF231722,
                appBg3 = 0xFF171627,
                panel = 0xFF271E26,
                panelSoft = 0xFF201820,
                border = 0xFFDA7797,
                shadow = 0xFF000000,
                text = 0xFFF4E2EA,
                heading = 0xFFFFF6FB,
                muted = 0xFFD4B7C3,
                subtle = 0xFFAA8C98,
                accent = 0xFFE17599,
                accentStrong = 0xFFFFD0DF,
                secondary = 0xFF8ACDDA,
                success = 0xFFBDEAF1,
                onAccent = 0xFF2C131D
            )
        ),
        EchoThemePreset(
            id = "peachSoda",
            label = "Peach Soda",
            light =             EchoThemePresetTone(
                appBg = 0xFFFFF2E8,
                appBg2 = 0xFFFFD6BD,
                appBg3 = 0xFFD7F4EE,
                panel = 0xFFFFFDF9,
                panelSoft = 0xFFFAEADC,
                border = 0xFFB3684C,
                shadow = 0xFF663A2A,
                text = 0xFF50392F,
                heading = 0xFF33231D,
                muted = 0xFF745D54,
                subtle = 0xFF9A8176,
                accent = 0xFFD96D4C,
                accentStrong = 0xFF9C3E26,
                secondary = 0xFF4D998F,
                success = 0xFF236B63,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF15110F,
                appBg2 = 0xFF241915,
                appBg3 = 0xFF10201F,
                panel = 0xFF271F1B,
                panelSoft = 0xFF201916,
                border = 0xFFDA7E56,
                shadow = 0xFF000000,
                text = 0xFFF4E3D8,
                heading = 0xFFFFF5EF,
                muted = 0xFFD2B8AC,
                subtle = 0xFFAA8E82,
                accent = 0xFFE27B58,
                accentStrong = 0xFFFFD2C1,
                secondary = 0xFF78C9BE,
                success = 0xFFB5EEE6,
                onAccent = 0xFF2C1710
            )
        ),
        EchoThemePreset(
            id = "mintCandy",
            label = "Mint Candy",
            light =             EchoThemePresetTone(
                appBg = 0xFFF6FFF8,
                appBg2 = 0xFFD7F2DF,
                appBg3 = 0xFFFFE5EC,
                panel = 0xFFFDFFFA,
                panelSoft = 0xFFE6F5E6,
                border = 0xFF5C896F,
                shadow = 0xFF325242,
                text = 0xFF33493E,
                heading = 0xFF1F3029,
                muted = 0xFF556F63,
                subtle = 0xFF789488,
                accent = 0xFF3F9274,
                accentStrong = 0xFF27664F,
                secondary = 0xFFB95168,
                success = 0xFF27664F,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF101512,
                appBg2 = 0xFF17231C,
                appBg3 = 0xFF23151B,
                panel = 0xFF1D2721,
                panelSoft = 0xFF17201B,
                border = 0xFF61B991,
                shadow = 0xFF000000,
                text = 0xFFE0F0E7,
                heading = 0xFFF5FFF8,
                muted = 0xFFB7D0C3,
                subtle = 0xFF8CA99A,
                accent = 0xFF6BC09B,
                accentStrong = 0xFFC3F5DF,
                secondary = 0xFFE28AA0,
                success = 0xFFC3F5DF,
                onAccent = 0xFF10261C
            )
        ),
        EchoThemePreset(
            id = "berryDream",
            label = "Berry Dream",
            light =             EchoThemePresetTone(
                appBg = 0xFFF8F5FF,
                appBg2 = 0xFFE2D9FB,
                appBg3 = 0xFFFFDDEC,
                panel = 0xFFFFFDFF,
                panelSoft = 0xFFEFE8FA,
                border = 0xFF725BA6,
                shadow = 0xFF47356D,
                text = 0xFF45395B,
                heading = 0xFF2D2440,
                muted = 0xFF655878,
                subtle = 0xFF877A9A,
                accent = 0xFF7657B8,
                accentStrong = 0xFF563995,
                secondary = 0xFFB64B7D,
                success = 0xFF625A24,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF11101A,
                appBg2 = 0xFF1B1730,
                appBg3 = 0xFF241421,
                panel = 0xFF201D2E,
                panelSoft = 0xFF1A1726,
                border = 0xFF9277D4,
                shadow = 0xFF000000,
                text = 0xFFE9E4F7,
                heading = 0xFFFBF8FF,
                muted = 0xFFC4BADD,
                subtle = 0xFF9C90B8,
                accent = 0xFF9A79DD,
                accentStrong = 0xFFDDD0FF,
                secondary = 0xFFE48AB5,
                success = 0xFFEEE2A8,
                onAccent = 0xFF1D1233
            )
        ),
        EchoThemePreset(
            id = "matchaCream",
            label = "Matcha Cream",
            light =             EchoThemePresetTone(
                appBg = 0xFFFBFAEB,
                appBg2 = 0xFFE1EDC9,
                appBg3 = 0xFFF6D9D7,
                panel = 0xFFFFFEF6,
                panelSoft = 0xFFECEFD4,
                border = 0xFF7C8E4F,
                shadow = 0xFF4C5632,
                text = 0xFF42452D,
                heading = 0xFF2B301D,
                muted = 0xFF62664A,
                subtle = 0xFF85896B,
                accent = 0xFF6E8F49,
                accentStrong = 0xFF4D6B2F,
                secondary = 0xFFA55258,
                success = 0xFF4D6B2F,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF12140E,
                appBg2 = 0xFF1D2215,
                appBg3 = 0xFF241716,
                panel = 0xFF22261C,
                panelSoft = 0xFF1C2017,
                border = 0xFF8BA658,
                shadow = 0xFF000000,
                text = 0xFFE8EDDB,
                heading = 0xFFFBFFE9,
                muted = 0xFFC6D0AD,
                subtle = 0xFF9BA785,
                accent = 0xFF95B766,
                accentStrong = 0xFFE5F5BD,
                secondary = 0xFFDD8D91,
                success = 0xFFE5F5BD,
                onAccent = 0xFF1D250F
            )
        ),
        EchoThemePreset(
            id = "lemonMochi",
            label = "Lemon Mochi",
            light =             EchoThemePresetTone(
                appBg = 0xFFFFFBE6,
                appBg2 = 0xFFF6E7AD,
                appBg3 = 0xFFEAF4FB,
                panel = 0xFFFFFEF5,
                panelSoft = 0xFFF7EECB,
                border = 0xFFB28D37,
                shadow = 0xFF624E20,
                text = 0xFF4C3F1C,
                heading = 0xFF332A10,
                muted = 0xFF706133,
                subtle = 0xFF94865A,
                accent = 0xFFC99A26,
                accentStrong = 0xFF8A6113,
                secondary = 0xFF5F9DB7,
                success = 0xFF3B6F83,
                onAccent = 0xFF241800
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF15140F,
                appBg2 = 0xFF221F13,
                appBg3 = 0xFF111B23,
                panel = 0xFF262319,
                panelSoft = 0xFF201D15,
                border = 0xFFCFA93F,
                shadow = 0xFF000000,
                text = 0xFFF5EED2,
                heading = 0xFFFFF9DF,
                muted = 0xFFD5C99A,
                subtle = 0xFFACA172,
                accent = 0xFFD5AA3A,
                accentStrong = 0xFFFFE59A,
                secondary = 0xFF8BC8DF,
                success = 0xFFC8ECF7,
                onAccent = 0xFF2A1D05
            )
        ),
        EchoThemePreset(
            id = "cottonCloud",
            label = "Cotton Cloud",
            light =             EchoThemePresetTone(
                appBg = 0xFFF8FBFF,
                appBg2 = 0xFFDFE9FF,
                appBg3 = 0xFFFFE5F0,
                panel = 0xFFFDFEFF,
                panelSoft = 0xFFE7EEFD,
                border = 0xFF6980BC,
                shadow = 0xFF33436F,
                text = 0xFF3A435C,
                heading = 0xFF20283C,
                muted = 0xFF5C6680,
                subtle = 0xFF818CA6,
                accent = 0xFF6C88D8,
                accentStrong = 0xFF3F5FB5,
                secondary = 0xFFB6507A,
                success = 0xFF57681D,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF10131D,
                appBg2 = 0xFF171D31,
                appBg3 = 0xFF241521,
                panel = 0xFF1D2231,
                panelSoft = 0xFF171C2A,
                border = 0xFF7E96E4,
                shadow = 0xFF000000,
                text = 0xFFE8EEFC,
                heading = 0xFFFBFDFF,
                muted = 0xFFC2CCE8,
                subtle = 0xFF98A4C5,
                accent = 0xFF8BA5F0,
                accentStrong = 0xFFDAE3FF,
                secondary = 0xFFE58DB3,
                success = 0xFFE4ECAA,
                onAccent = 0xFF11192C
            )
        ),
        EchoThemePreset(
            id = "melonCream",
            label = "Melon Cream",
            light =             EchoThemePresetTone(
                appBg = 0xFFF8FFF0,
                appBg2 = 0xFFDFF0C9,
                appBg3 = 0xFFFFE2D8,
                panel = 0xFFFDFFF8,
                panelSoft = 0xFFE7F1D8,
                border = 0xFF6D9348,
                shadow = 0xFF325229,
                text = 0xFF354827,
                heading = 0xFF213218,
                muted = 0xFF596F45,
                subtle = 0xFF7C9467,
                accent = 0xFF6CA344,
                accentStrong = 0xFF47752A,
                secondary = 0xFFB95E4C,
                success = 0xFF47752A,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF10160F,
                appBg2 = 0xFF172415,
                appBg3 = 0xFF251814,
                panel = 0xFF1D281C,
                panelSoft = 0xFF172116,
                border = 0xFF7BB852,
                shadow = 0xFF000000,
                text = 0xFFE8F3DC,
                heading = 0xFFF8FFE9,
                muted = 0xFFC3D8AD,
                subtle = 0xFF96B080,
                accent = 0xFF8CC76A,
                accentStrong = 0xFFD8F6BF,
                secondary = 0xFFE18D78,
                success = 0xFFD8F6BF,
                onAccent = 0xFF14270E
            )
        ),
        EchoThemePreset(
            id = "seaSaltJelly",
            label = "Sea Salt Jelly",
            light =             EchoThemePresetTone(
                appBg = 0xFFF1FFFB,
                appBg2 = 0xFFCFEEEA,
                appBg3 = 0xFFFFE3DD,
                panel = 0xFFFAFFFD,
                panelSoft = 0xFFDBF1EE,
                border = 0xFF48948D,
                shadow = 0xFF235250,
                text = 0xFF2B4D49,
                heading = 0xFF183633,
                muted = 0xFF4F716D,
                subtle = 0xFF73958F,
                accent = 0xFF3C9A92,
                accentStrong = 0xFF226F68,
                secondary = 0xFFB95B50,
                success = 0xFF226F68,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF0F1718,
                appBg2 = 0xFF152525,
                appBg3 = 0xFF241714,
                panel = 0xFF1A292A,
                panelSoft = 0xFF152223,
                border = 0xFF50BDB5,
                shadow = 0xFF000000,
                text = 0xFFDCF1EE,
                heading = 0xFFF2FFFC,
                muted = 0xFFB1D8D2,
                subtle = 0xFF86AEA9,
                accent = 0xFF67C9C0,
                accentStrong = 0xFFC2F5EF,
                secondary = 0xFFE28B7D,
                success = 0xFFC2F5EF,
                onAccent = 0xFF0D2826
            )
        ),
        EchoThemePreset(
            id = "caramelPudding",
            label = "Caramel Pudding",
            light =             EchoThemePresetTone(
                appBg = 0xFFFFF7E8,
                appBg2 = 0xFFF5D29B,
                appBg3 = 0xFFFFDCE6,
                panel = 0xFFFFFAF0,
                panelSoft = 0xFFF4DFB8,
                border = 0xFFB98245,
                shadow = 0xFF5D3718,
                text = 0xFF5A3A20,
                heading = 0xFF3A2511,
                muted = 0xFF7A5940,
                subtle = 0xFF9A7659,
                accent = 0xFFB7772F,
                accentStrong = 0xFF7F4B18,
                secondary = 0xFFD56F86,
                success = 0xFF7F4B18,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF18110B,
                appBg2 = 0xFF2A1B10,
                appBg3 = 0xFF2A1019,
                panel = 0xFF2B1C12,
                panelSoft = 0xFF21160F,
                border = 0xFFD68F45,
                shadow = 0xFF000000,
                text = 0xFFF1D8B7,
                heading = 0xFFFFF3DB,
                muted = 0xFFD5B58A,
                subtle = 0xFFB99568,
                accent = 0xFFE0A45C,
                accentStrong = 0xFFFFD79A,
                secondary = 0xFFF18AA7,
                success = 0xFFFFD79A,
                onAccent = 0xFF29170A
            )
        ),
        EchoThemePreset(
            id = "neonCandy",
            label = "Neon Candy",
            light =             EchoThemePresetTone(
                appBg = 0xFFF6F7FF,
                appBg2 = 0xFFE7DCFF,
                appBg3 = 0xFFD8FFF7,
                panel = 0xFFFFFFFF,
                panelSoft = 0xFFEFE9FF,
                border = 0xFF9275E8,
                shadow = 0xFF402D76,
                text = 0xFF46385F,
                heading = 0xFF241A3F,
                muted = 0xFF6A5A82,
                subtle = 0xFF8B7CA2,
                accent = 0xFF8B5CF6,
                accentStrong = 0xFF5B39B4,
                secondary = 0xFFD9468D,
                success = 0xFF5B39B4,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF101021,
                appBg2 = 0xFF1B1640,
                appBg3 = 0xFF102B2B,
                panel = 0xFF1F1B39,
                panelSoft = 0xFF16162B,
                border = 0xFF9B7CFF,
                shadow = 0xFF000000,
                text = 0xFFE7DCFF,
                heading = 0xFFF7F2FF,
                muted = 0xFFC4B5E8,
                subtle = 0xFF9F90CA,
                accent = 0xFFA989FF,
                accentStrong = 0xFFE1D7FF,
                secondary = 0xFFFF84BE,
                success = 0xFFE1D7FF,
                onAccent = 0xFF181033
            )
        ),
        EchoThemePreset(
            id = "nyanCat",
            label = "Nyan Cat",
            light =             EchoThemePresetTone(
                appBg = 0xFFFFF7FB,
                appBg2 = 0xFFD7F3FF,
                appBg3 = 0xFFEADCFF,
                panel = 0xFFFFFFFF,
                panelSoft = 0xFFEEF8FF,
                border = 0xFF7AA7D9,
                shadow = 0xFF4F4284,
                text = 0xFF475072,
                heading = 0xFF2B2F5F,
                muted = 0xFF697392,
                subtle = 0xFF6F768B,
                accent = 0xFFFF5F93,
                accentStrong = 0xFFCF3F75,
                secondary = 0xFF28B8F0,
                success = 0xFF2C7C70,
                onAccent = 0xFF2C131D
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF11132D,
                appBg2 = 0xFF172959,
                appBg3 = 0xFF35164B,
                panel = 0xFF1D2348,
                panelSoft = 0xFF161A38,
                border = 0xFF7AA7FF,
                shadow = 0xFF000000,
                text = 0xFFEAF1FF,
                heading = 0xFFFFF6FB,
                muted = 0xFFBFC9EE,
                subtle = 0xFF97A3D6,
                accent = 0xFFFF7FB0,
                accentStrong = 0xFFFFD1E5,
                secondary = 0xFF59D9FF,
                success = 0xFFA4F5E5,
                onAccent = 0xFF2B0F24
            )
        ),
        EchoThemePreset(
            id = "childrenDoodle",
            label = "Children Doodle",
            light =             EchoThemePresetTone(
                appBg = 0xFFFFF4DC,
                appBg2 = 0xFFFFD9EC,
                appBg3 = 0xFFD6F7FF,
                panel = 0xFFFFFAF0,
                panelSoft = 0xFFF9E7D0,
                border = 0xFF5F82C6,
                shadow = 0xFF4C3C5F,
                text = 0xFF42537A,
                heading = 0xFF203F83,
                muted = 0xFF6F7897,
                subtle = 0xFF786E89,
                accent = 0xFF566FDA,
                accentStrong = 0xFF244CAA,
                secondary = 0xFFFF6FA8,
                success = 0xFF287265,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF100D22,
                appBg2 = 0xFF1D1735,
                appBg3 = 0xFF0D2A32,
                panel = 0xFF221E37,
                panelSoft = 0xFF161327,
                border = 0xFFB19AFF,
                shadow = 0xFF02020C,
                text = 0xFFF6EDFF,
                heading = 0xFFFFF8FF,
                muted = 0xFFDCCFF4,
                subtle = 0xFFB6A8D7,
                accent = 0xFFFF8DBC,
                accentStrong = 0xFFFFE0EE,
                secondary = 0xFF7BE5D1,
                success = 0xFFCAFFF5,
                onAccent = 0xFF2B0B1C
            )
        ),
        EchoThemePreset(
            id = "wisteriaBubble",
            label = "Wisteria Bubble",
            light =             EchoThemePresetTone(
                appBg = 0xFFFBF7FF,
                appBg2 = 0xFFE8D9FF,
                appBg3 = 0xFFDCFFF4,
                panel = 0xFFFFFAFF,
                panelSoft = 0xFFEEE2FF,
                border = 0xFF9C82DF,
                shadow = 0xFF3A2A62,
                text = 0xFF4C3C68,
                heading = 0xFF2C2144,
                muted = 0xFF6F5F8C,
                subtle = 0xFF8D7DAB,
                accent = 0xFF8F6ED5,
                accentStrong = 0xFF6043A6,
                secondary = 0xFF3D9F87,
                success = 0xFF6043A6,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF13101D,
                appBg2 = 0xFF211A36,
                appBg3 = 0xFF10251F,
                panel = 0xFF211A32,
                panelSoft = 0xFF171423,
                border = 0xFFA88AFF,
                shadow = 0xFF000000,
                text = 0xFFE7DCFB,
                heading = 0xFFFBF7FF,
                muted = 0xFFC9B9E8,
                subtle = 0xFFA997CE,
                accent = 0xFFB99CFF,
                accentStrong = 0xFFEEE6FF,
                secondary = 0xFF7BE0C5,
                success = 0xFFEEE6FF,
                onAccent = 0xFF1C1230
            )
        ),
        EchoThemePreset(
            id = "strawberryCookie",
            label = "Strawberry Cookie",
            light =             EchoThemePresetTone(
                appBg = 0xFFFFF8F0,
                appBg2 = 0xFFF7DCC6,
                appBg3 = 0xFFFFE3EE,
                panel = 0xFFFFFAF4,
                panelSoft = 0xFFF4DFCF,
                border = 0xFFC9798A,
                shadow = 0xFF58312B,
                text = 0xFF5B3A32,
                heading = 0xFF3B211C,
                muted = 0xFF7C5D52,
                subtle = 0xFF9D7D72,
                accent = 0xFFD75A72,
                accentStrong = 0xFF9F3449,
                secondary = 0xFF9A672C,
                success = 0xFF9F3449,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF19100F,
                appBg2 = 0xFF2A1915,
                appBg3 = 0xFF291018,
                panel = 0xFF2B1B18,
                panelSoft = 0xFF211412,
                border = 0xFFE18196,
                shadow = 0xFF000000,
                text = 0xFFF1D2C9,
                heading = 0xFFFFF0E8,
                muted = 0xFFD9B2A4,
                subtle = 0xFFB98C7D,
                accent = 0xFFF08AA0,
                accentStrong = 0xFFFFD0DA,
                secondary = 0xFFE0B66C,
                success = 0xFFFFD0DA,
                onAccent = 0xFF321017
            )
        ),
        EchoThemePreset(
            id = "graphiteAurora",
            label = "Graphite Aurora",
            light =             EchoThemePresetTone(
                appBg = 0xFFF5F7F8,
                appBg2 = 0xFFDFE6E8,
                appBg3 = 0xFFD8F3EC,
                panel = 0xFFFBFCFC,
                panelSoft = 0xFFE8EEF0,
                border = 0xFF7A9698,
                shadow = 0xFF263739,
                text = 0xFF3F5053,
                heading = 0xFF1F292B,
                muted = 0xFF637174,
                subtle = 0xFF7F8D90,
                accent = 0xFF2F7F73,
                accentStrong = 0xFF1F5D55,
                secondary = 0xFF496A9F,
                success = 0xFF1F5D55,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF101416,
                appBg2 = 0xFF182123,
                appBg3 = 0xFF10241F,
                panel = 0xFF20292B,
                panelSoft = 0xFF171F21,
                border = 0xFF5FB4AA,
                shadow = 0xFF000000,
                text = 0xFFD4E3E1,
                heading = 0xFFEDF6F5,
                muted = 0xFFA8BCBA,
                subtle = 0xFF839A98,
                accent = 0xFF5EC4B5,
                accentStrong = 0xFFB2EFE6,
                secondary = 0xFF86A8E7,
                success = 0xFFB2EFE6,
                onAccent = 0xFF0B2824
            )
        ),
        EchoThemePreset(
            id = "amberNoir",
            label = "Amber Noir",
            light =             EchoThemePresetTone(
                appBg = 0xFFFBF7EE,
                appBg2 = 0xFFEAD9BB,
                appBg3 = 0xFFF3E7D4,
                panel = 0xFFFFFAF1,
                panelSoft = 0xFFEFE1C9,
                border = 0xFFB99662,
                shadow = 0xFF423120,
                text = 0xFF584737,
                heading = 0xFF33291E,
                muted = 0xFF7A6A59,
                subtle = 0xFF968676,
                accent = 0xFF9A6A24,
                accentStrong = 0xFF624015,
                secondary = 0xFF6A4B3A,
                success = 0xFF624015,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF11100E,
                appBg2 = 0xFF211A12,
                appBg3 = 0xFF2A2118,
                panel = 0xFF2A241C,
                panelSoft = 0xFF1D1914,
                border = 0xFFC89A4B,
                shadow = 0xFF000000,
                text = 0xFFEAD9BD,
                heading = 0xFFFFF3D8,
                muted = 0xFFC3AD8D,
                subtle = 0xFFA48D6A,
                accent = 0xFFD4A64C,
                accentStrong = 0xFFF5D78F,
                secondary = 0xFFB88763,
                success = 0xFFF5D78F,
                onAccent = 0xFF221405
            )
        ),
        EchoThemePreset(
            id = "oceanStudio",
            label = "Ocean Studio",
            light =             EchoThemePresetTone(
                appBg = 0xFFF4F8FB,
                appBg2 = 0xFFD8E8EF,
                appBg3 = 0xFFDCE3F2,
                panel = 0xFFFBFDFF,
                panelSoft = 0xFFE5EEF4,
                border = 0xFF7DA3B7,
                shadow = 0xFF2A404E,
                text = 0xFF415363,
                heading = 0xFF202D3A,
                muted = 0xFF607486,
                subtle = 0xFF7E91A1,
                accent = 0xFF2F7390,
                accentStrong = 0xFF1D526A,
                secondary = 0xFF596B9A,
                success = 0xFF1D526A,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF0F151B,
                appBg2 = 0xFF132332,
                appBg3 = 0xFF17203A,
                panel = 0xFF1E2A34,
                panelSoft = 0xFF16212B,
                border = 0xFF6CB1CF,
                shadow = 0xFF000000,
                text = 0xFFD4E5EF,
                heading = 0xFFEDF7FF,
                muted = 0xFFA9BFCE,
                subtle = 0xFF829AAB,
                accent = 0xFF68B4D4,
                accentStrong = 0xFFC2EAFF,
                secondary = 0xFF9AA7E8,
                success = 0xFFC2EAFF,
                onAccent = 0xFF0C2531
            )
        ),
        EchoThemePreset(
            id = "rosewoodVinyl",
            label = "Rosewood Vinyl",
            light =             EchoThemePresetTone(
                appBg = 0xFFFBF3EE,
                appBg2 = 0xFFEAD3C7,
                appBg3 = 0xFFF0DFE7,
                panel = 0xFFFFF8F4,
                panelSoft = 0xFFEFDCD3,
                border = 0xFFB27A73,
                shadow = 0xFF462623,
                text = 0xFF5C4240,
                heading = 0xFF35211F,
                muted = 0xFF7E6662,
                subtle = 0xFF9A817D,
                accent = 0xFF8F4D48,
                accentStrong = 0xFF66312D,
                secondary = 0xFF8B6A3E,
                success = 0xFF66312D,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF140F10,
                appBg2 = 0xFF251717,
                appBg3 = 0xFF201821,
                panel = 0xFF2A1D1D,
                panelSoft = 0xFF1E1516,
                border = 0xFFD18279,
                shadow = 0xFF000000,
                text = 0xFFEBD1CB,
                heading = 0xFFFFF0EB,
                muted = 0xFFC7AAA3,
                subtle = 0xFFA88680,
                accent = 0xFFD4827B,
                accentStrong = 0xFFF3B8AE,
                secondary = 0xFFD2A45C,
                success = 0xFFF3B8AE,
                onAccent = 0xFF2F1210
            )
        ),
        EchoThemePreset(
            id = "darkSideMoon",
            label = "Dark Side Moon",
            light =             EchoThemePresetTone(
                appBg = 0xFF171722,
                appBg2 = 0xFF202638,
                appBg3 = 0xFF151827,
                panel = 0xFF232635,
                panelSoft = 0xFF181B28,
                border = 0xFFC5D2E8,
                shadow = 0xFF03050E,
                text = 0xFFEEF2FB,
                heading = 0xFFFFF7DF,
                muted = 0xFFCAD4E7,
                subtle = 0xFF9FAEC8,
                accent = 0xFFF6F0D8,
                accentStrong = 0xFF8FDCFF,
                secondary = 0xFFFFD84F,
                success = 0xFF96F0C6,
                onAccent = 0xFF121521
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF10111A,
                appBg2 = 0xFF181D2B,
                appBg3 = 0xFF202337,
                panel = 0xFF1E212F,
                panelSoft = 0xFF131622,
                border = 0xFFCDDAF0,
                shadow = 0xFF000008,
                text = 0xFFEEF3FF,
                heading = 0xFFFFF8DF,
                muted = 0xFFCBD7EC,
                subtle = 0xFFA2B0CA,
                accent = 0xFFF7F1DC,
                accentStrong = 0xFF93DCFF,
                secondary = 0xFF28B8F0,
                success = 0xFF9DF0C7,
                onAccent = 0xFF10131D
            )
        ),
        EchoThemePreset(
            id = "shibuyaNight",
            label = "Shibuya Night",
            light =             EchoThemePresetTone(
                appBg = 0xFF1B0D2B,
                appBg2 = 0xFF3A185E,
                appBg3 = 0xFF073449,
                panel = 0xFF2A1F3A,
                panelSoft = 0xFF1D142D,
                border = 0xFFDA3796,
                shadow = 0xFF07030E,
                text = 0xFFF1E8FF,
                heading = 0xFFFFF6FF,
                muted = 0xFFCDBDE8,
                subtle = 0xFFA58CC3,
                accent = 0xFFFF3B9D,
                accentStrong = 0xFFFFD4EE,
                secondary = 0xFF23D0EE,
                success = 0xFFB9F8FF,
                onAccent = 0xFF26001A
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF070411,
                appBg2 = 0xFF120824,
                appBg3 = 0xFF061A24,
                panel = 0xFF170F26,
                panelSoft = 0xFF10091C,
                border = 0xFFF03AA4,
                shadow = 0xFF000000,
                text = 0xFFF0E5FF,
                heading = 0xFFFFF4FF,
                muted = 0xFFC7B5E4,
                subtle = 0xFF957CAD,
                accent = 0xFFFF2F98,
                accentStrong = 0xFFFFD3ED,
                secondary = 0xFF18D5F4,
                success = 0xFFB9F8FF,
                onAccent = 0xFF240018
            )
        ),
        EchoThemePreset(
            id = "kyotoKurenai",
            label = "Kyoto Kurenai",
            light =             EchoThemePresetTone(
                appBg = 0xFFFFF1DF,
                appBg2 = 0xFFE8B99B,
                appBg3 = 0xFFF7D989,
                panel = 0xFFFFF8ED,
                panelSoft = 0xFFF0D5B7,
                border = 0xFFA64D36,
                shadow = 0xFF5F2D20,
                text = 0xFF543124,
                heading = 0xFF30170F,
                muted = 0xFF755040,
                subtle = 0xFF966E5B,
                accent = 0xFFA92F26,
                accentStrong = 0xFF6E1D17,
                secondary = 0xFFC08A1E,
                success = 0xFF76520F,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF120807,
                appBg2 = 0xFF27100D,
                appBg3 = 0xFF241806,
                panel = 0xFF2A1914,
                panelSoft = 0xFF1D100D,
                border = 0xFFE6644F,
                shadow = 0xFF000000,
                text = 0xFFF4D8C6,
                heading = 0xFFFFF4E8,
                muted = 0xFFD5B39B,
                subtle = 0xFFAD8870,
                accent = 0xFFFF5F4A,
                accentStrong = 0xFFFFD2C4,
                secondary = 0xFFE3B23C,
                success = 0xFFF6DC91,
                onAccent = 0xFF310B06
            )
        ),
        EchoThemePreset(
            id = "ukiyoIndigo",
            label = "Ukiyo Indigo",
            light =             EchoThemePresetTone(
                appBg = 0xFFEAF1ED,
                appBg2 = 0xFF9FBCCB,
                appBg3 = 0xFFD8C094,
                panel = 0xFFFBFBF3,
                panelSoft = 0xFFD6E1DF,
                border = 0xFF4F7893,
                shadow = 0xFF1C3445,
                text = 0xFF314655,
                heading = 0xFF10283A,
                muted = 0xFF536B78,
                subtle = 0xFF768996,
                accent = 0xFF174F7F,
                accentStrong = 0xFF0D3659,
                secondary = 0xFFB06D1F,
                success = 0xFF0D3659,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF07101A,
                appBg2 = 0xFF0A2540,
                appBg3 = 0xFF211D15,
                panel = 0xFF172B40,
                panelSoft = 0xFF0D1D2E,
                border = 0xFF5EB3E2,
                shadow = 0xFF000000,
                text = 0xFFD8E8F4,
                heading = 0xFFEDF8FF,
                muted = 0xFFABC1D1,
                subtle = 0xFF849CAD,
                accent = 0xFF4AA6DD,
                accentStrong = 0xFFC5E7FF,
                secondary = 0xFFD59B43,
                success = 0xFFC5E7FF,
                onAccent = 0xFF041B2F
            )
        ),
        EchoThemePreset(
            id = "fujiSnow",
            label = "Fuji Snow",
            light =             EchoThemePresetTone(
                appBg = 0xFFEDF8FF,
                appBg2 = 0xFFBADCFF,
                appBg3 = 0xFFF5D1E6,
                panel = 0xFFFBFDFF,
                panelSoft = 0xFFD8ECFF,
                border = 0xFF5B89D0,
                shadow = 0xFF234069,
                text = 0xFF344860,
                heading = 0xFF12233D,
                muted = 0xFF536983,
                subtle = 0xFF758AA4,
                accent = 0xFF246FC8,
                accentStrong = 0xFF174B90,
                secondary = 0xFFC74786,
                success = 0xFF174B90,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF08111F,
                appBg2 = 0xFF10244A,
                appBg3 = 0xFF2A1430,
                panel = 0xFF182438,
                panelSoft = 0xFF0F192B,
                border = 0xFF6B9BEB,
                shadow = 0xFF000000,
                text = 0xFFE2ECFF,
                heading = 0xFFF8FBFF,
                muted = 0xFFB7C9E6,
                subtle = 0xFF8CA3C3,
                accent = 0xFF6B9BEB,
                accentStrong = 0xFFD7E7FF,
                secondary = 0xFFF07DB7,
                success = 0xFFD7E7FF,
                onAccent = 0xFF071936
            )
        ),
        EchoThemePreset(
            id = "matsuriLantern",
            label = "Matsuri Lantern",
            light =             EchoThemePresetTone(
                appBg = 0xFFFFF0D8,
                appBg2 = 0xFFEFAE67,
                appBg3 = 0xFFFFD35F,
                panel = 0xFFFFF7E9,
                panelSoft = 0xFFF2D4A7,
                border = 0xFFB75A2F,
                shadow = 0xFF65331C,
                text = 0xFF553323,
                heading = 0xFF35180D,
                muted = 0xFF77513D,
                subtle = 0xFF9A7159,
                accent = 0xFFC23C28,
                accentStrong = 0xFF842116,
                secondary = 0xFFD88409,
                success = 0xFF7C4A05,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF120706,
                appBg2 = 0xFF2D100B,
                appBg3 = 0xFF2A1A05,
                panel = 0xFF311C15,
                panelSoft = 0xFF21100C,
                border = 0xFFF67C48,
                shadow = 0xFF000000,
                text = 0xFFF5D5C2,
                heading = 0xFFFFF1E2,
                muted = 0xFFD8AD91,
                subtle = 0xFFB48769,
                accent = 0xFFFF5A3C,
                accentStrong = 0xFFFFD0BF,
                secondary = 0xFFFFB72E,
                success = 0xFFFFE19A,
                onAccent = 0xFF340C05
            )
        ),
        EchoThemePreset(
            id = "ginzaNoir",
            label = "Ginza Noir",
            light =             EchoThemePresetTone(
                appBg = 0xFFEBE5DA,
                appBg2 = 0xFFC7BCA8,
                appBg3 = 0xFFC2CBD5,
                panel = 0xFFFAF7EF,
                panelSoft = 0xFFE0D8C7,
                border = 0xFF8A7650,
                shadow = 0xFF2F2B25,
                text = 0xFF413B33,
                heading = 0xFF1C1C1D,
                muted = 0xFF665D50,
                subtle = 0xFF867C6C,
                accent = 0xFF72530E,
                accentStrong = 0xFF4A3507,
                secondary = 0xFF2F668E,
                success = 0xFF4A3507,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF090A0D,
                appBg2 = 0xFF111219,
                appBg3 = 0xFF1B1712,
                panel = 0xFF1D1D24,
                panelSoft = 0xFF111218,
                border = 0xFFD6B158,
                shadow = 0xFF000000,
                text = 0xFFE8DFCE,
                heading = 0xFFFFF5E5,
                muted = 0xFFC2B5A1,
                subtle = 0xFF9D907F,
                accent = 0xFFD6B158,
                accentStrong = 0xFFFFE1A0,
                secondary = 0xFF66A8D4,
                success = 0xFFFFE1A0,
                onAccent = 0xFF1F1604
            )
        ),
        EchoThemePreset(
            id = "frostJazz",
            label = "Frost Jazz",
            light =             EchoThemePresetTone(
                appBg = 0xFFEAF2FB,
                appBg2 = 0xFFAAC2DF,
                appBg3 = 0xFFD4C0DC,
                panel = 0xFFFBFDFF,
                panelSoft = 0xFFD9E5F2,
                border = 0xFF5C7DA9,
                shadow = 0xFF22344F,
                text = 0xFF34495F,
                heading = 0xFF142234,
                muted = 0xFF546A80,
                subtle = 0xFF778A9F,
                accent = 0xFF245F9E,
                accentStrong = 0xFF163F70,
                secondary = 0xFF7F3E70,
                success = 0xFF163F70,
                onAccent = 0xFFFFFFFF
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF080D15,
                appBg2 = 0xFF101B2C,
                appBg3 = 0xFF201426,
                panel = 0xFF182434,
                panelSoft = 0xFF0E1724,
                border = 0xFF5C8FD3,
                shadow = 0xFF000000,
                text = 0xFFDEEBFB,
                heading = 0xFFF5F9FF,
                muted = 0xFFB1C4DC,
                subtle = 0xFF879DB7,
                accent = 0xFF5C8FD3,
                accentStrong = 0xFFD1E4FF,
                secondary = 0xFFC06A9E,
                success = 0xFFD1E4FF,
                onAccent = 0xFF07182D
            )
        ),
        EchoThemePreset(
            id = "FINAL",
            label = "FINAL",
            light =             EchoThemePresetTone(
                appBg = 0xFFEFEDE7,
                appBg2 = 0xFFD4CFC4,
                appBg3 = 0xFFFFFAF0,
                panel = 0xFFFFFDF7,
                panelSoft = 0xFFE2DDD3,
                border = 0xFF7E7565,
                shadow = 0xFF2E2A23,
                text = 0xFF39352F,
                heading = 0xFF171511,
                muted = 0xFF6A6258,
                subtle = 0xFF918777,
                accent = 0xFFB78943,
                accentStrong = 0xFF5B3F1C,
                secondary = 0xFF3F4850,
                success = 0xFF5B3F1C,
                onAccent = 0xFFFFFAF0
            ),
            dark =             EchoThemePresetTone(
                appBg = 0xFF0F0E0C,
                appBg2 = 0xFF1D1914,
                appBg3 = 0xFF15171A,
                panel = 0xFF23201C,
                panelSoft = 0xFF181716,
                border = 0xFFB29C76,
                shadow = 0xFF000000,
                text = 0xFFE8DFD0,
                heading = 0xFFFFF7E8,
                muted = 0xFFE8DFD0,
                subtle = 0xFFE8DFD0,
                accent = 0xFFD0A05A,
                accentStrong = 0xFFF5D69B,
                secondary = 0xFFAAB1B4,
                success = 0xFFAAB1B4,
                onAccent = 0xFF1A1206
            )
        )
    )

    private val byId: Map<String, EchoThemePreset> = all.associateBy { it.id }

    val ids: Array<String> = all.map { it.id }.toTypedArray()

    fun contains(id: String?): Boolean = id != null && byId.containsKey(id)

    fun labelFor(id: String?): String? = byId[id]?.label

    fun paletteFor(id: String?, dark: Boolean): EchoPalette? {
        val preset = byId[id] ?: return null
        return (if (dark) preset.dark else preset.light).toPalette()
    }
}
